# -*- coding: utf-8 -*-
"""ML0101EN-Proj-Loan-py-v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14geDu_dIWmJsjyX1RRV43b7iKoDQuAHv

<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align="center"><font size="5">Classification with Python</font></h1>

In this notebook we try to practice all the classification algorithms that we have learned in this course.

We load a dataset using Pandas library, and apply the following algorithms, and find the best one for this specific dataset by accuracy evaluation methods.

Let's first load required libraries:
"""

# Commented out IPython magic to ensure Python compatibility.
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing   
# %matplotlib inline

"""### About dataset

This dataset is about past loans. The **Loan_train.csv** data set includes details of 346 customers whose loan are already paid off or defaulted. It includes following fields:

| Field          | Description                                                                           |
| -------------- | ------------------------------------------------------------------------------------- |
| Loan_status    | Whether a loan is paid off on in collection                                           |
| Principal      | Basic principal loan amount at the                                                    |
| Terms          | Origination terms which can be weekly (7 days), biweekly, and monthly payoff schedule |
| Effective_date | When the loan got originated and took effects                                         |
| Due_date       | Since it’s one-time payoff schedule, each loan has one single due date                |
| Age            | Age of applicant                                                                      |
| Education      | Education of applicant                                                                |
| Gender         | The gender of applicant                                                               |

Let's download the dataset
"""

!wget -O loan_train.csv https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/FinalModule_Coursera/data/loan_train.csv

"""### Load Data From CSV File

"""

df = pd.read_csv('loan_train.csv')
df.head(10)

df.shape

"""### Convert to date time object

"""

df['due_date'] = pd.to_datetime(df['due_date'])
df['effective_date'] = pd.to_datetime(df['effective_date'])
df.head()

"""# Data visualization and pre-processing

Let’s see how many of each class is in our data set
"""

df['loan_status'].value_counts()

"""260 people have paid off the loan on time while 86 have gone into collection

Let's plot some columns to underestand data better:
"""

# notice: installing seaborn might takes a few minutes
!conda install -c anaconda seaborn -y

import seaborn as sns

bins = np.linspace(df.Principal.min(), df.Principal.max(), 10)
g = sns.FacetGrid(df, col="Gender", hue="loan_status", palette="Set1", col_wrap=2)
g.map(plt.hist, 'Principal', bins=bins, ec="k")

g.axes[-1].legend()
plt.show()

bins = np.linspace(df.age.min(), df.age.max(), 10)
g = sns.FacetGrid(df, col="Gender", hue="loan_status", palette="Set1", col_wrap=2)
g.map(plt.hist, 'age', bins=bins, ec="k")

g.axes[-1].legend()
plt.show()

"""# Pre-processing:  Feature selection/extraction

### Let's look at the day of the week people get the loan
"""

df['dayofweek'] = df['effective_date'].dt.dayofweek
bins = np.linspace(df.dayofweek.min(), df.dayofweek.max(), 10)
g = sns.FacetGrid(df, col="Gender", hue="loan_status", palette="Set1", col_wrap=2)
g.map(plt.hist, 'dayofweek', bins=bins, ec="k")
g.axes[-1].legend()
plt.show()

"""We see that people who get the loan at the end of the week don't pay it off, so let's use Feature binarization to set a threshold value less than day 4

"""

df['weekend'] = df['dayofweek'].apply(lambda x: 1 if (x>3)  else 0)
df.head()

"""## Convert Categorical features to numerical values

Let's look at gender:
"""

df.groupby(['Gender'])['loan_status'].value_counts(normalize=True)

"""86 % of female pay there loans while only 73 % of males pay there loan

Let's convert male to 0 and female to 1:
"""

df['Gender'].replace(to_replace=['male','female'], value=[0,1],inplace=True)
df.head()

"""## One Hot Encoding

#### How about education?

"""

df.groupby(['education'])['loan_status'].value_counts(normalize=True)

"""#### Features before One Hot Encoding

"""

df[['Principal','terms','age','Gender','education']].head()

"""#### Use one hot encoding technique to conver categorical varables to binary variables and append them to the feature Data Frame

"""

Feature = df[['Principal','terms','age','Gender','weekend']]
Feature = pd.concat([Feature,pd.get_dummies(df['education'])], axis=1)
Feature.drop(['Master or Above'], axis = 1,inplace=True)
Feature.head()

"""### Feature Selection

Let's define feature sets, X:
"""

X = Feature
X[0:5]

"""What are our lables?

"""

y = df['loan_status'].values
y[0:5]

"""## Normalize Data

Data Standardization give data zero mean and unit variance (technically should be done after train test split)
"""

X= preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

"""# Classification

Now, it is your turn, use the training set to build an accurate model. Then use the test set to report the accuracy of the model
You should use the following algorithm:

*   K Nearest Neighbor(KNN)
*   Decision Tree
*   Support Vector Machine
*   Logistic Regression

\__ Notice:\__

*   You can go above and change the pre-processing, feature selection, feature-extraction, and so on, to make a better model.
*   You should use either scikit-learn, Scipy or Numpy libraries for developing the classification algorithms.
*   You should include the code of the algorithm in the following cells.

# K Nearest Neighbor(KNN)

Notice: You should find the best k to build the model with the best accuracy.\
**warning:** You should not use the **loan_test.csv** for finding the best k, however, you can split your train_loan.csv into train and test to find the best **k**.
"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 4)
print("Training shape: ", X_train.shape, y_train.shape)
print("Testing shape: ", X_test.shape, y_test.shape)

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

Ks = 10
mean_acc = np.zeros((Ks-1))
std_acc = np.zeros((Ks-1))

for n in range(1,Ks):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(y_test, yhat)

    
    std_acc[n-1]=np.std(yhat==y_test)/np.sqrt(yhat.shape[0])

mean_acc

plt.plot(range(1,Ks),mean_acc,'g')
plt.fill_between(range(1,Ks),mean_acc - 1 * std_acc,mean_acc + 1 * std_acc, alpha=0.10)
plt.fill_between(range(1,Ks),mean_acc - 3 * std_acc,mean_acc + 3 * std_acc, alpha=0.10,color="green")
plt.legend(('Accuracy ', '+/- 1xstd','+/- 3xstd'))
plt.ylabel('Accuracy ')
plt.xlabel('Number of Neighbors (K)')
plt.tight_layout()
plt.show()

print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1)

from sklearn.metrics import f1_score
f1_score(y_test, yhat, average='weighted')

"""# Decision Tree

"""

from sklearn.tree import DecisionTreeClassifier

LoanTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
LoanTree.fit(X_train, y_train)

predTree = LoanTree.predict(X_test)
print(predTree[0:5])
print(y_test[0:5])

from sklearn.metrics import accuracy_score
print("Training Accuracy using F1-score: ", f1_score(y_train, LoanTree.predict(X_train), average='weighted'))
print("Testing Accuracy using F1-score: ", f1_score(y_test, predTree, average='weighted'))

print("")

print("DecisionTrees's Training Accuracy: ", metrics.accuracy_score(y_train, LoanTree.predict(X_train)))
print("DecisionTrees's Testing Accuracy: ", metrics.accuracy_score(y_test, predTree))

"""# Support Vector Machine

"""

from sklearn import svm

clf = svm.SVC(kernel = 'rbf')
clf.fit(X_train, y_train)

y_hat_svm = clf.predict(X_test)
y_hat_svm[0:5]

print("F1-score:", f1_score(y_test, y_hat_svm, average='weighted')) 

print("")

print("Training accuracy using jaccard-index: ", accuracy_score(y_train, clf.predict(X_train)))
print("Testing accuracy using jaccard-index: ", accuracy_score(y_test, y_hat_svm))

"""# Logistic Regression

"""

from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C = 0.01, solver = 'liblinear').fit(X_train, y_train)

y_hat_LR = LR.predict(X_test)
y_hat_LR

from sklearn.metrics import log_loss
prob_LR = LR.predict_proba(X_test)
prob_LR

print("")
print("F1-score:", f1_score(y_test, y_hat_LR, average='weighted')) 
print("")
print("Training accuracy using jaccard-index: ", accuracy_score(y_train, LR.predict(X_train)))
print("Testing accuracy using jaccard-index: ", accuracy_score(y_test, y_hat_LR))

print("")

print("Log Loss: ", log_loss(y_test, prob_LR))

"""# Model Evaluation using Test set

"""

from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

"""First, download and load the test set:

"""

!wget -O loan_test.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/loan_test.csv

"""### Load Test set for evaluation

"""

test_df = pd.read_csv('loan_test.csv')
test_df.head()

test_df['Gender'].replace(to_replace=['male','female'], value=[0,1],inplace=True)
Feature_test = test_df[['Principal','terms','age','Gender']]
Feature_test = pd.concat([Feature_test,pd.get_dummies(test_df['education'])], axis=1)

#Feature_test.drop(['Master or Above'], axis = 1,inplace=True)
Feature_test.head()

testX = Feature_test

testX = preprocessing.StandardScaler().fit(testX).transform(testX)

test_Y = pd.get_dummies(test_df['loan_status'].values)

test_Y.drop(['COLLECTION'], axis = 1, inplace = True)


print(test_Y.head())
print(testX.shape)

# Decision Tree Evaluation
y_DT = LoanTree.predict(testX)
y_DT = [1 if x == 'PAIDOFF' else 0 for x in y_DT]
knn_f1Score = f1_score(test_Y, y_DT)
print("Decision Tree F1_Score:", knn_f1Score)
print("Decision Tree Jaccard Score: ",jaccard_score(test_Y, y_DT))

# KNN Evaluation
y_knn = neigh.predict(testX)
y_knn = [1 if x == 'PAIDOFF' else 0 for x in y_knn]
print("KNN F1_Score:", f1_score(test_Y, y_knn))
print("KNN Jaccard Score:", jaccard_score(test_Y, y_knn))

# Support Vector Machine Evaluation
y_svm = clf.predict(testX)
y_svm = [1 if x == 'PAIDOFF' else 0 for x in y_svm]
print("SVM F1-Score:", f1_score(test_Y, y_svm))
print("SVM Jaccard Score:", jaccard_score(test_Y, y_svm))

# Logistic Regression Evaluation
y_LR = LR.predict(testX)
y_LR = [1 if x == 'PAIDOFF' else 0 for x in y_LR]
print("Logistic Regreesion F1-Score: ", f1_score(test_Y, y_LR))
print("Logistic Refression Jaccard Score:", jaccard_score(test_Y, y_LR ))
probability = LR.predict_proba(testX)
print("Log Loss: ", log_loss(test_Y, probability))

"""# Report

You should be able to report the accuracy of the built model using different evaluation metrics:

| Algorithm          | Jaccard | F1-score | LogLoss |
| ------------------ | ------- | -------- | ------- |
| KNN                | 0.722222       | 0.838710        | NA      |
| Decision Tree      | 0.740741       | 0.851064        | NA      |
| SVM                | 0.685185       | 0.813187        | NA      |
| LogisticRegression | 0.592593       | 0.744186        | 0.668622       |

The Decision Tree classfier is the best classifier for this dataset

<h2>Want to learn more?</h2>

IBM SPSS Modeler is a comprehensive analytics platform that has many machine learning algorithms. It has been designed to bring predictive intelligence to decisions made by individuals, by groups, by systems – by your enterprise as a whole. A free trial is available through this course, available here: <a href="http://cocl.us/ML0101EN-SPSSModeler?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">SPSS Modeler</a>

Also, you can use Watson Studio to run these notebooks faster with bigger datasets. Watson Studio is IBM's leading cloud solution for data scientists, built by data scientists. With Jupyter notebooks, RStudio, Apache Spark and popular libraries pre-packaged in the cloud, Watson Studio enables data scientists to collaborate on their projects without having to install anything. Join the fast-growing community of Watson Studio users today with a free account at <a href="https://cocl.us/ML0101EN_DSX?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">Watson Studio</a>

<h3>Thanks for completing this lesson!</h3>

<h4>Author:  <a href="https://ca.linkedin.com/in/saeedaghabozorgi?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">Saeed Aghabozorgi</a></h4>
<p><a href="https://ca.linkedin.com/in/saeedaghabozorgi">Saeed Aghabozorgi</a>, PhD is a Data Scientist in IBM with a track record of developing enterprise level applications that substantially increases clients’ ability to turn data into actionable knowledge. He is a researcher in data mining field and expert in developing advanced analytic methods like machine learning and statistical modelling on large datasets.</p>

<hr>

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description                                                             |
| ----------------- | ------- | ------------- | ------------------------------------------------------------------------------ |
| 2020-10-27        | 2.1     | Lakshmi Holla | Made changes in import statement due to updates in version of  sklearn library |
| 2020-08-27        | 2.0     | Malika Singla | Added lab to GitLab                                                            |

<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>

<p>
"""

